"""
DRISHTI-AI — Database Setup, Seeding, and Session Management
"""
import os
import sys
import json
import random
import string
from datetime import datetime, timedelta

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, Session

# Add project root to path
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from backend.app.models.models import Base, Incident, CitizenReport, ResponseTeam, Alert, Location

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./drishti.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {},
    echo=False,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_tables():
    Base.metadata.create_all(bind=engine)


def random_id(prefix: str, length: int = 6) -> str:
    return f"{prefix}-{''.join(random.choices(string.digits, k=length))}"


# ── Seed Data ─────────────────────────────────────────────────────────────────

DEMO_INCIDENTS = [
    {
        "incident_id": "BIH-FLD-024",
        "location": "Nawada, Bihar",
        "state": "Bihar",
        "district": "Nawada",
        "disaster_type": "flood",
        "severity": "CRITICAL",
        "status": "ACTIVE",
        "risk_score": 91.0,
        "risk_category": "CRITICAL",
        "probability": 94.0,
        "affected_population": 3500,
        "latitude": 24.8879,
        "longitude": 85.5443,
        "description": "Heavy rainfall for 72 hours causing major flooding. River Phalgu is overflowing. 3500+ residents displaced.",
        "rainfall": 92.0, "river_level": 88.0, "population_density": 78.0,
        "historical_disaster_freq": 82.0, "infrastructure_vulnerability": 76.0,
        "weather_severity": 89.0, "distance_to_hospital": 45.0, "road_accessibility": 30.0,
        "feature_contributions": {"rainfall": 28.0, "river_level": 24.0, "population_density": 17.0,
                                   "historical_disaster_freq": 12.0, "infrastructure_vulnerability": 10.0},
        "ai_explanation": "Heavy rainfall combined with rapidly increasing river levels, high population exposure and historical flood vulnerability indicates a critical flood risk. Immediate evacuation recommended.",
        "recommended_actions": ["Issue immediate evacuation order for all flood-prone zones",
                                 "Deploy NDRF teams to Nawada district",
                                 "Open emergency relief camps at elevated locations",
                                 "Monitor Phalgu river gauge continuously",
                                 "Coordinate medical teams for emergency response",
                                 "Alert neighboring districts for support"],
        "priority": "P1",
        "report_count": 47,
        "source": "citizen+sensor",
        "detected_at": datetime.utcnow() - timedelta(hours=2),
    },
    {
        "incident_id": "ASS-FLD-011",
        "location": "Goalpara, Assam",
        "state": "Assam",
        "district": "Goalpara",
        "disaster_type": "flood",
        "severity": "CRITICAL",
        "status": "ACTIVE",
        "risk_score": 87.0,
        "risk_category": "CRITICAL",
        "probability": 91.0,
        "affected_population": 8200,
        "latitude": 26.1719,
        "longitude": 90.6195,
        "description": "Brahmaputra river dangerously high. Multiple villages submerged. Over 8200 people need immediate evacuation.",
        "rainfall": 85.0, "river_level": 94.0, "population_density": 82.0,
        "historical_disaster_freq": 90.0, "infrastructure_vulnerability": 70.0,
        "weather_severity": 85.0, "distance_to_hospital": 55.0, "road_accessibility": 25.0,
        "feature_contributions": {"rainfall": 24.0, "river_level": 28.0, "population_density": 19.0,
                                   "historical_disaster_freq": 10.0, "infrastructure_vulnerability": 6.0},
        "ai_explanation": "Brahmaputra river at dangerously high levels. Combined with historical flood frequency in Assam and high population exposure, critical flood risk persists. Immediate action required.",
        "recommended_actions": ["Immediate full-scale evacuation of riverside villages",
                                 "Deploy boats for rescue operations",
                                 "Establish relief camps on elevated ground",
                                 "Alert Brahmaputra Flood Control Board",
                                 "Pre-position medical supplies"],
        "priority": "P1",
        "report_count": 31,
        "source": "citizen+sensor",
        "detected_at": datetime.utcnow() - timedelta(hours=4),
    },
    {
        "incident_id": "ODI-CYC-007",
        "location": "Puri, Odisha",
        "state": "Odisha",
        "district": "Puri",
        "disaster_type": "cyclone",
        "severity": "HIGH",
        "status": "ACTIVE",
        "risk_score": 79.0,
        "risk_category": "CRITICAL",
        "probability": 88.0,
        "affected_population": 12000,
        "latitude": 19.8135,
        "longitude": 85.8312,
        "description": "Cyclone depression intensifying in Bay of Bengal. Wind speed 110 kmph. Coastal communities under high threat.",
        "rainfall": 70.0, "river_level": 45.0, "population_density": 75.0,
        "historical_disaster_freq": 88.0, "infrastructure_vulnerability": 65.0,
        "weather_severity": 92.0, "distance_to_hospital": 20.0, "road_accessibility": 60.0,
        "feature_contributions": {"weather_severity": 26.0, "historical_disaster_freq": 22.0,
                                   "population_density": 18.0, "rainfall": 8.0, "river_level": 5.0},
        "ai_explanation": "Intensifying cyclonic storm with high wind speeds and storm surge potential. Puri's coastal location and historical cyclone history indicate critical threat. Immediate coastal evacuation needed.",
        "recommended_actions": ["Issue cyclone red alert for coastal districts",
                                 "Evacuate coastal communities to cyclone shelters",
                                 "Secure fishing vessels at sea",
                                 "Pre-position NDRF teams in Puri",
                                 "Coordinate with Indian Meteorological Department"],
        "priority": "P1",
        "report_count": 22,
        "source": "sensor+weather",
        "detected_at": datetime.utcnow() - timedelta(hours=6),
    },
    {
        "incident_id": "UKH-LSL-003",
        "location": "Chamoli, Uttarakhand",
        "state": "Uttarakhand",
        "district": "Chamoli",
        "disaster_type": "landslide",
        "severity": "HIGH",
        "status": "ACTIVE",
        "risk_score": 74.0,
        "risk_category": "HIGH",
        "probability": 82.0,
        "affected_population": 650,
        "latitude": 30.4085,
        "longitude": 79.3202,
        "description": "Massive landslide blocking NH-07. Several vehicles trapped. Continuous rainfall increasing instability risk.",
        "rainfall": 78.0, "river_level": 55.0, "population_density": 35.0,
        "historical_disaster_freq": 75.0, "infrastructure_vulnerability": 80.0,
        "weather_severity": 70.0, "distance_to_hospital": 70.0, "road_accessibility": 15.0,
        "feature_contributions": {"infrastructure_vulnerability": 22.0, "historical_disaster_freq": 20.0,
                                   "rainfall": 18.0, "distance_to_hospital": 8.0, "road_accessibility": 6.0},
        "ai_explanation": "Active landslide on critical highway. Poor road accessibility severely limits rescue operations. Continuous rainfall increases secondary slide risk. Urgent search and rescue needed.",
        "recommended_actions": ["Deploy SDRF search and rescue teams",
                                 "Close NH-07 for all traffic",
                                 "Arrange helicopter rescue for trapped persons",
                                 "Establish alternative route for emergency vehicles",
                                 "Monitor slope stability continuously"],
        "priority": "P1",
        "report_count": 15,
        "source": "citizen+patrol",
        "detected_at": datetime.utcnow() - timedelta(hours=3),
    },
    {
        "incident_id": "WB-FLD-019",
        "location": "Malda, West Bengal",
        "state": "West Bengal",
        "district": "Malda",
        "disaster_type": "flood",
        "severity": "HIGH",
        "status": "ACTIVE",
        "risk_score": 68.0,
        "risk_category": "HIGH",
        "probability": 79.0,
        "affected_population": 5400,
        "latitude": 25.0109,
        "longitude": 88.1415,
        "description": "Ganga river rising steadily. Embankment breach in two locations. Agricultural land submerged.",
        "rainfall": 65.0, "river_level": 78.0, "population_density": 70.0,
        "historical_disaster_freq": 72.0, "infrastructure_vulnerability": 60.0,
        "weather_severity": 65.0, "distance_to_hospital": 30.0, "road_accessibility": 50.0,
        "feature_contributions": {"river_level": 22.0, "population_density": 20.0,
                                   "rainfall": 16.0, "historical_disaster_freq": 6.0, "weather_severity": 4.0},
        "ai_explanation": "Rising Ganga river with embankment breaches creating imminent flood threat. High population density in affected area requires urgent pre-positioning of relief resources.",
        "recommended_actions": ["Issue flood warning for embankment-breach zones",
                                 "Repair embankment breaches urgently",
                                 "Pre-position relief materials at district level",
                                 "Alert Malda district administration",
                                 "Arrange alternate accommodation for affected families"],
        "priority": "P2",
        "report_count": 28,
        "source": "citizen+sensor",
        "detected_at": datetime.utcnow() - timedelta(hours=5),
    },
    {
        "incident_id": "MAH-FLD-033",
        "location": "Kolhapur, Maharashtra",
        "state": "Maharashtra",
        "district": "Kolhapur",
        "disaster_type": "flood",
        "severity": "HIGH",
        "status": "MONITORING",
        "risk_score": 62.0,
        "risk_category": "HIGH",
        "probability": 74.0,
        "affected_population": 2100,
        "latitude": 16.7050,
        "longitude": 74.2433,
        "description": "Panchganga river nearing danger mark. Urban flooding in low-lying areas. Pre-monsoon warnings issued.",
        "rainfall": 68.0, "river_level": 72.0, "population_density": 65.0,
        "historical_disaster_freq": 68.0, "infrastructure_vulnerability": 55.0,
        "weather_severity": 60.0, "distance_to_hospital": 15.0, "road_accessibility": 65.0,
        "feature_contributions": {"rainfall": 20.0, "river_level": 18.0,
                                   "population_density": 14.0, "historical_disaster_freq": 6.0, "weather_severity": 4.0},
        "ai_explanation": "Panchganga approaching danger levels. Urban flooding underway in low-lying areas. Proactive evacuation of vulnerable communities and riverbank residents strongly recommended.",
        "recommended_actions": ["Issue flood preparedness advisory",
                                 "Identify and evacuate residents from low-lying areas",
                                 "Monitor Panchganga river levels hourly",
                                 "Deploy pump sets for urban drainage",
                                 "Alert hospitals to prepare for possible surge"],
        "priority": "P2",
        "report_count": 19,
        "source": "citizen",
        "detected_at": datetime.utcnow() - timedelta(hours=8),
    },
    {
        "incident_id": "KER-FLD-014",
        "location": "Wayanad, Kerala",
        "state": "Kerala",
        "district": "Wayanad",
        "disaster_type": "landslide",
        "severity": "MEDIUM",
        "status": "MONITORING",
        "risk_score": 55.0,
        "risk_category": "HIGH",
        "probability": 68.0,
        "affected_population": 820,
        "latitude": 11.6854,
        "longitude": 76.1320,
        "description": "Slope instability reported in tribal hamlets after 3 days of heavy rainfall. Early warning issued.",
        "rainfall": 75.0, "river_level": 50.0, "population_density": 40.0,
        "historical_disaster_freq": 65.0, "infrastructure_vulnerability": 62.0,
        "weather_severity": 68.0, "distance_to_hospital": 60.0, "road_accessibility": 40.0,
        "feature_contributions": {"rainfall": 22.0, "historical_disaster_freq": 18.0,
                                   "infrastructure_vulnerability": 10.0, "distance_to_hospital": 3.0, "road_accessibility": 2.0},
        "ai_explanation": "Rainfall-induced slope instability in Wayanad's tribal areas. Historical landslide vulnerability and limited road accessibility elevate the risk. Monitoring and preventive evacuation advised.",
        "recommended_actions": ["Pre-emptive evacuation of at-risk hamlets",
                                 "Monitor soil moisture and slope sensors",
                                 "Deploy geotechnical team for assessment",
                                 "Open community centers as temporary shelters",
                                 "Maintain communication with tribal area wardens"],
        "priority": "P2",
        "report_count": 11,
        "source": "citizen+patrol",
        "detected_at": datetime.utcnow() - timedelta(hours=10),
    },
    {
        "incident_id": "GUJ-CYC-002",
        "location": "Veraval, Gujarat",
        "state": "Gujarat",
        "district": "Gir Somnath",
        "disaster_type": "cyclone",
        "severity": "MEDIUM",
        "status": "MONITORING",
        "risk_score": 48.0,
        "risk_category": "MEDIUM",
        "probability": 61.0,
        "affected_population": 3200,
        "latitude": 20.9024,
        "longitude": 70.3609,
        "description": "Low-pressure system in Arabian Sea. Coastal advisory issued. Fishermen warned to return to shore.",
        "rainfall": 45.0, "river_level": 30.0, "population_density": 55.0,
        "historical_disaster_freq": 60.0, "infrastructure_vulnerability": 50.0,
        "weather_severity": 65.0, "distance_to_hospital": 25.0, "road_accessibility": 70.0,
        "feature_contributions": {"weather_severity": 20.0, "historical_disaster_freq": 18.0,
                                   "population_density": 6.0, "rainfall": 2.0, "river_level": 2.0},
        "ai_explanation": "Developing low-pressure system requires monitoring. Gujarat coastline historically prone to cyclones. Pre-emptive measures and coastal advisory already in place. Situation under control.",
        "recommended_actions": ["Maintain coastal watch and weather monitoring",
                                 "Advise fishermen to stay onshore",
                                 "Keep NDRF teams on standby",
                                 "Inspect cyclone shelters for readiness",
                                 "Update alerts every 6 hours based on IMD reports"],
        "priority": "P3",
        "report_count": 8,
        "source": "weather+patrol",
        "detected_at": datetime.utcnow() - timedelta(hours=12),
    },
    {
        "incident_id": "HP-LSL-008",
        "location": "Mandi, Himachal Pradesh",
        "state": "Himachal Pradesh",
        "district": "Mandi",
        "disaster_type": "landslide",
        "severity": "MEDIUM",
        "status": "ACTIVE",
        "risk_score": 58.0,
        "risk_category": "HIGH",
        "probability": 72.0,
        "affected_population": 450,
        "latitude": 31.7070,
        "longitude": 76.9316,
        "description": "Series of small landslides blocking mountain road. 450 tourists stranded. Rescue operations underway.",
        "rainfall": 70.0, "river_level": 45.0, "population_density": 30.0,
        "historical_disaster_freq": 70.0, "infrastructure_vulnerability": 75.0,
        "weather_severity": 62.0, "distance_to_hospital": 65.0, "road_accessibility": 10.0,
        "feature_contributions": {"infrastructure_vulnerability": 24.0, "historical_disaster_freq": 20.0,
                                   "rainfall": 10.0, "road_accessibility": 4.0, "distance_to_hospital": 0.0},
        "ai_explanation": "Multiple landslides creating isolation risk for trapped tourists. Extremely poor road accessibility combined with remote location limits rescue options. Air rescue may be necessary.",
        "recommended_actions": ["Deploy helicopter for aerial rescue assessment",
                                 "Clear landslide debris from access roads urgently",
                                 "Ensure food/water supply for stranded tourists",
                                 "Coordinate with district administration",
                                 "Monitor for additional slide risk before road clearing"],
        "priority": "P2",
        "report_count": 13,
        "source": "citizen",
        "detected_at": datetime.utcnow() - timedelta(hours=7),
    },
    {
        "incident_id": "RAJ-DRT-005",
        "location": "Barmer, Rajasthan",
        "state": "Rajasthan",
        "district": "Barmer",
        "disaster_type": "drought",
        "severity": "MEDIUM",
        "status": "MONITORING",
        "risk_score": 42.0,
        "risk_category": "MEDIUM",
        "probability": 58.0,
        "affected_population": 15000,
        "latitude": 25.7463,
        "longitude": 71.3924,
        "description": "Severe deficit rainfall in Barmer district. Agricultural water sources critically low. Livestock distress reported.",
        "rainfall": 10.0, "river_level": 5.0, "population_density": 45.0,
        "historical_disaster_freq": 55.0, "infrastructure_vulnerability": 60.0,
        "weather_severity": 50.0, "distance_to_hospital": 50.0, "road_accessibility": 60.0,
        "feature_contributions": {"historical_disaster_freq": 18.0, "population_density": 14.0,
                                   "infrastructure_vulnerability": 6.0, "weather_severity": 2.0, "rainfall": 2.0},
        "ai_explanation": "Chronic drought conditions in Barmer. Significant rainfall deficit affecting agriculture and water security. Large population exposure with historically limited water infrastructure increases vulnerability.",
        "recommended_actions": ["Activate emergency water supply tanker services",
                                 "Assess crop damage for compensation",
                                 "Provide fodder for livestock in distress",
                                 "Monitor drinking water quality",
                                 "Connect farmers with MNREGA emergency work"],
        "priority": "P3",
        "report_count": 6,
        "source": "citizen+survey",
        "detected_at": datetime.utcnow() - timedelta(hours=24),
    },
    {
        "incident_id": "MNP-EQK-001",
        "location": "Imphal, Manipur",
        "state": "Manipur",
        "district": "Imphal West",
        "disaster_type": "earthquake",
        "severity": "LOW",
        "status": "MONITORING",
        "risk_score": 32.0,
        "risk_category": "MEDIUM",
        "probability": 52.0,
        "affected_population": 1200,
        "latitude": 24.8170,
        "longitude": 93.9368,
        "description": "Magnitude 3.8 earthquake felt in Imphal. Minor tremors reported. No major damage confirmed yet.",
        "rainfall": 15.0, "river_level": 20.0, "population_density": 55.0,
        "historical_disaster_freq": 68.0, "infrastructure_vulnerability": 52.0,
        "weather_severity": 15.0, "distance_to_hospital": 15.0, "road_accessibility": 75.0,
        "feature_contributions": {"historical_disaster_freq": 22.0, "population_density": 8.0,
                                   "infrastructure_vulnerability": 2.0, "rainfall": 0.0, "river_level": 0.0},
        "ai_explanation": "Minor earthquake with no immediate critical damage. Manipur's location in seismic zone makes aftershock monitoring important. Structural assessments of older buildings recommended.",
        "recommended_actions": ["Conduct rapid structural damage assessment",
                                 "Monitor seismic activity for aftershocks",
                                 "Alert hospitals for possible casualty surge",
                                 "Inspect critical infrastructure (bridges, dams)",
                                 "Provide public information to reduce panic"],
        "priority": "P3",
        "report_count": 4,
        "source": "sensor",
        "detected_at": datetime.utcnow() - timedelta(hours=1),
    },
    {
        "incident_id": "MH-FIRE-012",
        "location": "Nashik, Maharashtra",
        "state": "Maharashtra",
        "district": "Nashik",
        "disaster_type": "fire",
        "severity": "HIGH",
        "status": "ACTIVE",
        "risk_score": 76.0,
        "risk_category": "CRITICAL",
        "probability": 85.0,
        "affected_population": 380,
        "latitude": 20.0059,
        "longitude": 73.7912,
        "description": "Forest fire spreading rapidly in Nashik forest range. Wind-driven fire approaching residential areas.",
        "rainfall": 5.0, "river_level": 10.0, "population_density": 50.0,
        "historical_disaster_freq": 45.0, "infrastructure_vulnerability": 55.0,
        "weather_severity": 82.0, "distance_to_hospital": 20.0, "road_accessibility": 60.0,
        "feature_contributions": {"weather_severity": 24.0, "population_density": 14.0,
                                   "historical_disaster_freq": 8.0, "infrastructure_vulnerability": 6.0, "rainfall": 0.0},
        "ai_explanation": "Active forest fire with strong wind conditions creating rapid spread risk. Proximity to residential zones makes this a high-priority incident. Air support for fire suppression may be required.",
        "recommended_actions": ["Deploy fire suppression teams with aerial support",
                                 "Evacuate residential areas in fire path",
                                 "Establish firebreak lines to contain spread",
                                 "Alert forest department and SDRF",
                                 "Pre-position medical teams for burn casualties"],
        "priority": "P1",
        "report_count": 17,
        "source": "citizen+patrol",
        "detected_at": datetime.utcnow() - timedelta(hours=3, minutes=30),
    },
]

DEMO_TEAMS = [
    {"team_id": "NDRF-01", "team_name": "NDRF Battalion 1", "team_type": "NDRF",
     "location": "Patna, Bihar", "state": "Bihar", "status": "DEPLOYED",
     "assigned_incident": "BIH-FLD-024", "eta_minutes": 45, "personnel_count": 45,
     "capabilities": ["flood rescue", "boat operations", "medical first aid"],
     "contact": "+91-9800-NDRF-01", "latitude": 25.5941, "longitude": 85.1376},
    {"team_id": "NDRF-02", "team_name": "NDRF Battalion 2", "team_type": "NDRF",
     "location": "Guwahati, Assam", "state": "Assam", "status": "DEPLOYED",
     "assigned_incident": "ASS-FLD-011", "eta_minutes": 90, "personnel_count": 45,
     "capabilities": ["flood rescue", "boat operations", "heavy rescue"],
     "contact": "+91-9800-NDRF-02", "latitude": 26.1445, "longitude": 91.7362},
    {"team_id": "SDRF-OD", "team_name": "Odisha SDRF Team Alpha", "team_type": "SDRF",
     "location": "Bhubaneswar, Odisha", "state": "Odisha", "status": "DEPLOYED",
     "assigned_incident": "ODI-CYC-007", "eta_minutes": 120, "personnel_count": 30,
     "capabilities": ["cyclone response", "coastal rescue", "relief distribution"],
     "contact": "+91-9800-SDRF-OD", "latitude": 20.2961, "longitude": 85.8245},
    {"team_id": "MED-01", "team_name": "Emergency Medical Team Alpha", "team_type": "Medical",
     "location": "Dehradun, Uttarakhand", "state": "Uttarakhand", "status": "DEPLOYED",
     "assigned_incident": "UKH-LSL-003", "eta_minutes": 180, "personnel_count": 15,
     "capabilities": ["trauma care", "emergency surgery", "evacuation support"],
     "contact": "+91-9800-MED-01", "latitude": 30.3165, "longitude": 78.0322},
    {"team_id": "FIRE-MH", "team_name": "Maharashtra Fire & Rescue", "team_type": "Fire & Rescue",
     "location": "Pune, Maharashtra", "state": "Maharashtra", "status": "DEPLOYED",
     "assigned_incident": "MH-FIRE-012", "eta_minutes": 60, "personnel_count": 25,
     "capabilities": ["fire suppression", "chemical rescue", "structural rescue"],
     "contact": "+91-9800-FIRE-01", "latitude": 18.5204, "longitude": 73.8567},
    {"team_id": "NDRF-03", "team_name": "NDRF Battalion 3", "team_type": "NDRF",
     "location": "Kolkata, West Bengal", "state": "West Bengal", "status": "AVAILABLE",
     "assigned_incident": None, "eta_minutes": None, "personnel_count": 45,
     "capabilities": ["flood rescue", "boat operations", "search and rescue"],
     "contact": "+91-9800-NDRF-03", "latitude": 22.5726, "longitude": 88.3639},
    {"team_id": "VOL-01", "team_name": "Local Volunteer Force Alpha", "team_type": "Volunteers",
     "location": "Jaipur, Rajasthan", "state": "Rajasthan", "status": "AVAILABLE",
     "assigned_incident": None, "eta_minutes": None, "personnel_count": 60,
     "capabilities": ["relief distribution", "evacuation support", "community outreach"],
     "contact": "+91-9800-VOL-01", "latitude": 26.9124, "longitude": 75.7873},
    {"team_id": "MED-02", "team_name": "Emergency Medical Team Beta", "team_type": "Medical",
     "location": "Chennai, Tamil Nadu", "state": "Tamil Nadu", "status": "AVAILABLE",
     "assigned_incident": None, "eta_minutes": None, "personnel_count": 12,
     "capabilities": ["trauma care", "field surgery", "mass casualty management"],
     "contact": "+91-9800-MED-02", "latitude": 13.0827, "longitude": 80.2707},
    {"team_id": "POLICE-GUJ", "team_name": "Gujarat Police Emergency Unit", "team_type": "Police",
     "location": "Ahmedabad, Gujarat", "state": "Gujarat", "status": "DEPLOYED",
     "assigned_incident": "GUJ-CYC-002", "eta_minutes": 90, "personnel_count": 30,
     "capabilities": ["crowd management", "evacuation", "law enforcement"],
     "contact": "+91-9800-POL-GJ", "latitude": 23.0225, "longitude": 72.5714},
    {"team_id": "SDRF-KA", "team_name": "Karnataka SDRF Team", "team_type": "SDRF",
     "location": "Bengaluru, Karnataka", "state": "Karnataka", "status": "BUSY",
     "assigned_incident": None, "eta_minutes": None, "personnel_count": 25,
     "capabilities": ["flood response", "earthquake response", "urban search rescue"],
     "contact": "+91-9800-SDRF-KA", "latitude": 12.9716, "longitude": 77.5946},
    {"team_id": "NDRF-04", "team_name": "NDRF Battalion 4 Rapid Response", "team_type": "NDRF",
     "location": "Delhi", "state": "Delhi", "status": "AVAILABLE",
     "assigned_incident": None, "eta_minutes": None, "personnel_count": 45,
     "capabilities": ["multi-hazard response", "CBRN", "specialized rescue"],
     "contact": "+91-9800-NDRF-04", "latitude": 28.6139, "longitude": 77.2090},
    {"team_id": "AIR-01", "team_name": "IAF Helicopter Rescue Unit", "team_type": "Air Support",
     "location": "Chandigarh", "state": "Punjab", "status": "DEPLOYED",
     "assigned_incident": "HP-LSL-008", "eta_minutes": 40, "personnel_count": 8,
     "capabilities": ["aerial rescue", "air evacuation", "disaster survey"],
     "contact": "+91-9800-AIR-01", "latitude": 30.7333, "longitude": 76.7794},
]

DEMO_ALERTS = [
    {
        "alert_id": "ALT-001", "incident_id": "BIH-FLD-024", "alert_type": "RISK_ESCALATION",
        "severity": "CRITICAL", "title": "Flood Risk Escalated — Bihar Zone 3",
        "message": "Flood risk in Nawada, Bihar has escalated significantly. River Phalgu gauge at 92% capacity.",
        "previous_risk": 78.0, "current_risk": 91.0,
        "change_reason": "Rapid river level increase (6 cm/hour) and rainfall exceeding danger threshold",
        "acknowledged": False,
        "created_at": datetime.utcnow() - timedelta(minutes=18),
    },
    {
        "alert_id": "ALT-002", "incident_id": "MH-FIRE-012", "alert_type": "NEW_INCIDENT",
        "severity": "CRITICAL", "title": "Forest Fire Approaching Residential Area — Nashik",
        "message": "Active forest fire in Nashik Forest Range spreading towards residential zones. Wind speed 35 kmph.",
        "previous_risk": 0.0, "current_risk": 76.0,
        "change_reason": "New high-severity incident detected. Wind-driven spread risk.",
        "acknowledged": False,
        "created_at": datetime.utcnow() - timedelta(minutes=35),
    },
    {
        "alert_id": "ALT-003", "incident_id": "ASS-FLD-011", "alert_type": "RISK_ESCALATION",
        "severity": "CRITICAL", "title": "Brahmaputra River at Danger Level — Assam",
        "message": "Brahmaputra river level at 94% of danger threshold. 8,200+ people at immediate risk of displacement.",
        "previous_risk": 72.0, "current_risk": 87.0,
        "change_reason": "Upstream rainfall and river level surge. Embankment stress detected.",
        "acknowledged": False,
        "created_at": datetime.utcnow() - timedelta(hours=1, minutes=12),
    },
    {
        "alert_id": "ALT-004", "incident_id": "ODI-CYC-007", "alert_type": "WEATHER_WARNING",
        "severity": "HIGH", "title": "Cyclone Intensification — Bay of Bengal",
        "message": "Cyclonic system intensifying. IMD forecasts landfall near Puri coast within 18 hours.",
        "previous_risk": 65.0, "current_risk": 79.0,
        "change_reason": "Cyclone intensified from depression to severe cyclonic storm category",
        "acknowledged": False,
        "created_at": datetime.utcnow() - timedelta(hours=2),
    },
    {
        "alert_id": "ALT-005", "incident_id": "WB-FLD-019", "alert_type": "INFRASTRUCTURE",
        "severity": "HIGH", "title": "Embankment Breach Confirmed — Malda",
        "message": "Two embankment breaches confirmed on Ganga riverbank in Malda district. Water entering agricultural areas.",
        "previous_risk": 55.0, "current_risk": 68.0,
        "change_reason": "Embankment breach reported by district authorities. River level continues rising.",
        "acknowledged": True,
        "created_at": datetime.utcnow() - timedelta(hours=3),
    },
]


def seed_database(db: Session):
    """Seed the database with demo data if it's empty."""

    # Check if already seeded
    if db.query(Incident).count() > 0:
        return

    print("🌱 Seeding database with demo data...")

    # Seed incidents
    for inc_data in DEMO_INCIDENTS:
        inc = Incident(**inc_data)
        db.add(inc)

    # Seed response teams
    for team_data in DEMO_TEAMS:
        team = ResponseTeam(**team_data)
        db.add(team)

    # Seed alerts
    for alert_data in DEMO_ALERTS:
        alert = Alert(**alert_data)
        db.add(alert)

    db.commit()
    print(f"✅ Seeded {len(DEMO_INCIDENTS)} incidents, {len(DEMO_TEAMS)} teams, {len(DEMO_ALERTS)} alerts")
